project_id = "rugged-abacus-464109-r7"
region = "us-central1"
local_vpc_name = "my-app2-vpc"
local_subnet_name = "my-app2-subnet"
local_subnet_cidr = "10.8.0.0/16"
local_vm_name = "my-app2-vm"
local_machine_type = "e2-medium"
local_zone = "us-central1-a"